services:
  cvat_server:
    image: cvat/server:v2.20.0
    environment:
      CVAT_HOST: localhost
      DJANGO_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
    volumes:
      - C:\Users\Sippler\Documents\TruckPilot\tools\vision-training-collector\data\final:/home/django/share/truckpilot:ro
  cvat_ui:
    image: cvat/ui:v2.20.0
  cvat_utils:
    image: cvat/server:v2.20.0
    environment:
      CVAT_HOST: localhost
      DJANGO_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
  cvat_worker_import:
    image: cvat/server:v2.20.0
    environment:
      CVAT_HOST: localhost
      DJANGO_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
    volumes:
      - C:\Users\Sippler\Documents\TruckPilot\tools\vision-training-collector\data\final:/home/django/share/truckpilot:ro
  cvat_worker_export:
    image: cvat/server:v2.20.0
    environment:
      CVAT_HOST: localhost
      DJANGO_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
  cvat_worker_annotation:
    image: cvat/server:v2.20.0
    environment:
      CVAT_HOST: localhost
      DJANGO_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8080,http://localhost'
  traefik:
    profiles: ["disabled"]
  nginx_proxy:
    image: nginx:alpine
    container_name: cvat_nginx_proxy
    networks:
      - cvat_cvat
    ports:
      - "8080:80"
    depends_on:
      - cvat_server
      - cvat_ui
    volumes:
      - C:\Users\Sippler\Documents\TruckPilot\tools\cvat-setup\nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  cvat_cvat:
    external: true