//! Real-image NCC templates for `SpeedMapper`, derived from labeled
//! crops collected by the Phase 6.5h pipeline.
//!
//! **DO NOT EDIT BY HAND.** Regenerated by
//! `tools/model-tools/build_sign_templates.py` from
//! `tools/model-tools/sign_crops_labeled/<kmh>/*.png`. Re-run the
//! script whenever new labeled crops land.
//!
//! Each entry is `(km/h, &[u8; 1024])` — a 32×32 grayscale, row-major
//! template. Multiple entries per km/h are allowed (one per labeled
//! crop) so `SpeedMapper::match_speed` can pick the best-matching
//! exemplar across font/perspective/lighting variants.
//!
//! When this slice is empty, `SpeedMapper` falls back to the synthetic
//! 5×7-bitmap-font templates from `speed_mapper.rs`.

#[allow(dead_code)] // populated by the build script; empty placeholder by default
pub const REAL_TEMPLATES: &[(u32, &[u8; 1024])] = &[];
