"""Generate `speed_templates_real.rs` from labeled sign crops.

Reads ``tools/model-tools/sign_crops/<kmh>/*.png`` (where the user has
hand-grouped extract_sign_crops.py output by km/h value), normalises
each crop to a 32×32 grayscale row-major byte array, and writes one
entry per crop into
``crates/plugins/sign-vision/src/speed_templates_real.rs``. The Rust
``SpeedMapper`` then tries real templates first and falls back to
synthetic 5×7-bitmap-font templates for any km/h value with no real
exemplars.

Subdirs whose name isn't a positive integer (e.g. ``_mapped/``) are
skipped, so the extractor's reference dir doesn't pollute the
training set.

Multiple entries per km/h are intentional: each crop becomes its own
exemplar so NCC matching can pick the best across font / lighting /
perspective variants. Memory budget is generous: 32×32 = 1024 bytes per
template; 100 templates = 100 KB.

Install
-------
    pip install Pillow

Usage
-----
    python tools/model-tools/build_sign_templates.py

After running:
    cargo build -p truckpilot-plugin-sign-vision --release
    cargo xtask copy-plugins
    # restart daemon, run live test, check sign.class.SpeedLimitSign.km_unmapped.total

Re-run after every fresh labeling pass.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
LABELED_DIR = REPO_ROOT / "tools" / "model-tools" / "sign_crops"
OUTPUT_RS = (
    REPO_ROOT / "crates" / "plugins" / "sign-vision" / "src" / "speed_templates_real.rs"
)
TEMPLATE_SIZE = 32  # must match TEMPLATE_SIZE in speed_mapper.rs


def crop_to_template(path: Path) -> bytes:
    """Load PNG, convert to grayscale, resize to TEMPLATE_SIZE×TEMPLATE_SIZE,
    return row-major bytes (length 1024 for 32×32)."""
    try:
        from PIL import Image
    except ImportError:
        sys.stderr.write("Pillow not installed. pip install Pillow\n")
        sys.exit(2)

    with Image.open(path) as im:
        # `LANCZOS` preserves sign edges better than `NEAREST` when down-
        # sampling from typical bbox sizes (~60-180 px) to 32 px.
        im = im.convert("L").resize((TEMPLATE_SIZE, TEMPLATE_SIZE), Image.LANCZOS)
        return im.tobytes()


def collect_templates() -> dict[int, list[tuple[Path, bytes]]]:
    """Walk LABELED_DIR/<kmh>/*.png. Returns {kmh: [(path, bytes), ...]}.
    Skips directories whose names aren't positive integers."""
    if not LABELED_DIR.is_dir():
        sys.stderr.write(f"labeled dir not found: {LABELED_DIR}\n")
        sys.exit(2)

    out: dict[int, list[tuple[Path, bytes]]] = {}
    for sub in sorted(LABELED_DIR.iterdir()):
        if not sub.is_dir():
            continue
        try:
            kmh = int(sub.name)
        except ValueError:
            print(f"  skip non-numeric dir: {sub.name}")
            continue
        if kmh <= 0:
            continue
        pngs = sorted(sub.glob("*.png"))
        if not pngs:
            continue
        rows: list[tuple[Path, bytes]] = []
        for png in pngs:
            try:
                rows.append((png, crop_to_template(png)))
            except Exception as exc:  # noqa: BLE001
                print(f"  warn: failed to load {png}: {exc}")
        out[kmh] = rows
    return out


def emit_rust(templates: dict[int, list[tuple[Path, bytes]]]) -> str:
    """Render the Rust source. One const byte array per crop, then one
    slice tying everything together. Sorted by km/h then filename for
    deterministic output."""
    lines: list[str] = [
        "//! Real-image NCC templates for `SpeedMapper`, derived from labeled",
        "//! crops collected by the Phase 6.5h pipeline.",
        "//!",
        "//! **DO NOT EDIT BY HAND.** Regenerated by",
        "//! `tools/model-tools/build_sign_templates.py` from",
        "//! `tools/model-tools/sign_crops/<kmh>/*.png`. Re-run the",
        "//! script whenever new labeled crops land.",
        "//!",
        "//! Each entry is `(km/h, &[u8; 1024])` — a 32×32 grayscale, row-major",
        "//! template. Multiple entries per km/h are allowed (one per labeled",
        "//! crop) so `SpeedMapper::match_speed` can pick the best-matching",
        "//! exemplar across font/perspective/lighting variants.",
        "//!",
        "//! When this slice is empty, `SpeedMapper` falls back to the synthetic",
        "//! 5×7-bitmap-font templates from `speed_mapper.rs`.",
        "",
    ]
    if not templates:
        lines.append("#[allow(dead_code)]")
        lines.append("pub const REAL_TEMPLATES: &[(u32, &[u8; 1024])] = &[];")
        return "\n".join(lines) + "\n"

    # Per-crop const byte arrays. Naming: T_<kmh>_<index>.
    entries: list[str] = []  # (kmh, const_name) for the final slice
    for kmh in sorted(templates.keys()):
        for idx, (_path, data) in enumerate(templates[kmh]):
            assert len(data) == TEMPLATE_SIZE * TEMPLATE_SIZE, (
                f"template for {kmh} has unexpected length {len(data)}"
            )
            const_name = f"T_{kmh}_{idx}"
            lines.append(f"#[rustfmt::skip]")
            lines.append(f"const {const_name}: [u8; 1024] = [")
            for chunk_start in range(0, 1024, 16):
                chunk = data[chunk_start : chunk_start + 16]
                lines.append("    " + ", ".join(str(b) for b in chunk) + ",")
            lines.append("];")
            lines.append("")
            entries.append((kmh, const_name))

    lines.append("pub const REAL_TEMPLATES: &[(u32, &[u8; 1024])] = &[")
    for kmh, const_name in entries:
        lines.append(f"    ({kmh}, &{const_name}),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    templates = collect_templates()
    total_crops = sum(len(v) for v in templates.values())
    print(f"Found {len(templates)} km/h classes, {total_crops} crops total:")
    for kmh in sorted(templates.keys()):
        print(f"  {kmh:>3} km/h : {len(templates[kmh])} crops")

    if total_crops == 0:
        print("\nNo crops found — leaving placeholder in place.")
        return

    rs = emit_rust(templates)
    OUTPUT_RS.write_text(rs, encoding="utf-8")
    print(f"\nWrote {OUTPUT_RS}")
    print("Next: cargo build -p truckpilot-plugin-sign-vision --release && cargo xtask copy-plugins")


if __name__ == "__main__":
    main()
