"""TruckPilot VMM-2 — Minimap OpenCV sidecar."""

HEADER_MAGIC = b"TPM1"
HEADER_VERSION = 1
HEADER_BYTES = 64
MAX_POINTS = 256
POINT_BYTES = 8  # two f32 (x, y)
PAYLOAD_BYTES = MAX_POINTS * POINT_BYTES
BUFFER_BYTES = HEADER_BYTES + PAYLOAD_BYTES
DEFAULT_SHM_NAME = "TruckPilotMinimapLine"
DEFAULT_FPS = 10
